const courses = [
  { name: "CTI" },
  { name: "Editorial" },
  { name: "MVC Architecture" },
  { name: "SSCP" },
  { name: "Clinical Development" },
  { name: "KOL Management" },
  { name: "CTC" },
  { name: "GGY Axis" },
  { name: "Public Administration" },
  { name: "SRDF" },
  { name: "US Tax" },
  { name: "SWAT" },
  { name: "ABAP Web Dynpro" },
  { name: "Information Technology" },
  { name: "RPD" },
  { name: "z/VM" },
  { name: "Fashion Blogging" },
  { name: "Consulting" },
  { name: "Pro-IV" },
  { name: "CNC Operation" },
  { name: "HSE auditing" },
  { name: "Tax Research" },
  { name: "OA Framework" },
  { name: "MMA" },
  { name: "CTRS" },
  { name: "ASP.NET" },
  { name: "Wellbeing" },
  { name: "Military Experience" },
  { name: "MBS" },
  { name: "TVCs" },
  { name: "RTC" },
  { name: "RhinoCAM" },
  { name: "TBMCS" },
  { name: "DDA compliance" },
  { name: "Fire Alarm" },
  { name: "OEMs" },
  { name: "European Affairs" },
  { name: "IAS 39" },
  { name: "FFT" },
  { name: "Xserve" },
  { name: "VTR" },
  { name: "LSS" },
  { name: "CMYK" },
  { name: "Customer Support" },
  { name: "BTS" },
  { name: "Cybercrime" },
  { name: "CBI" },
  { name: "Structural Dynamics" },
  { name: "PMO set-up" },
  { name: "RSpec" },
  { name: "PMO" },
  { name: "Tumblr" },
  { name: "PVC" },
  { name: "UCC filings" },
  { name: "Background Checks" },
  { name: "VMware Player" },
  { name: "RF Design" },
  { name: "DJ" },
  { name: "Zen Shiatsu" },
  { name: "Alarm Systems" },
  { name: "Utility Construction" },
  { name: "Customer Relations" },
  { name: "Segregation of Duties" },
  { name: "Museums" },
  { name: "JTA" },
  { name: "PVD" },
  { name: "TPP" },
  { name: "RPM" },
  { name: "Three.js" },
  { name: "SRST" },
  { name: "BSI Tax Factory" },
  { name: "Functional Verification" },
  { name: "Supply Chain" },
  { name: "FX Trading" },
  { name: "CBM" },
  { name: "German" },
  { name: "Mystery Shopping" },
  { name: "OAB" },
  { name: "European Affairs" },
  { name: "Cardiology" },
  { name: "SQL" },
  { name: "LTSpice" },
  { name: "Luxury Cruise" },
  { name: "Industrial Hygiene" },
  { name: "Motivational Interviewing" },
  { name: "OEMs" },
  { name: "QML" },
  { name: "IBM Mainframe" },
  { name: "NCDA" },
  { name: "DST" },
  { name: "Rhinoceros" },
  { name: "Turbines" },
  { name: "Administrative Law" },
  { name: "Medical Ultrasound" },
  { name: "Yii" },
  { name: "Secretarial Skills" },
  { name: "Hyperion HFM" },
  { name: "Psychological Assessment" },
  { name: "Branding" },
  { name: "Contemporary Art" },
  { name: "Shotokan Karate" },
  { name: "ADP ezLaborManager" },
  { name: "NVU" },
  { name: "SSCP" },
  { name: "VSTO" },
  { name: "Cybercrime" },
  { name: "MD-11" },
  { name: "Logistics" },
  { name: "Combined Cycle" },
  { name: "CISA" },
  { name: "FSC Certification" },
  { name: "Human Capital" },
  { name: "Oil Sands" },
  { name: "Enterprise Architecture" },
  { name: "Sleep Medicine" },
  { name: "Architectural Drawings" },
  { name: "Cd" },
  { name: "MBCS" },
  { name: "vShield" },
  { name: "DTDs" },
  { name: "EMR" },
  { name: "OGC" },
  { name: "Google Apps" },
  { name: "American Welding Society (AWS)" },
  { name: "EOS" },
  { name: "SPSS" },
  { name: "Beauty Industry" },
  { name: "Executive Administrative Assistance" },
  { name: "RS Means" },
  { name: "MPLS VPN" },
  { name: "Venture Capital" },
  { name: "Area Rugs" },
  { name: "Road Safety" },
  { name: "GNU Octave" },
  { name: "Nanotechnology" },
  { name: "Overseeing Projects" },
  { name: "TMF" },
  { name: "Entity Framework" },
  { name: "Employee Management" },
  { name: "Overall Wellness" },
  { name: "QFD" },
  { name: "NI LabVIEW" },
  { name: "Two-factor Authentication" },
  { name: "Observational Astronomy" },
  { name: "Object Oriented Design" },
  { name: "Online Reputation Management" },
  { name: "Public Sector" },
  { name: "Phone Etiquette" },
  { name: "Flame AA" },
  { name: "Classroom Management" },
  { name: "JDE One World" },
  { name: "Customs Regulations" },
  { name: "RDO" },
  { name: "5 Why" },
  { name: "European Union Politics" },
  { name: "XML Programming" },
  { name: "Google Analytics" },
  { name: "Drywall" },
  { name: "RTGS" },
  { name: "RRP" },
  { name: "Interior Architecture" },
  { name: "MSP Practitioner" },
  { name: "Special Events Coordination" },
  { name: "Umbrellas" },
  { name: "Toad" },
  { name: "XPDL" },
  { name: "LSO" },
  { name: "Production Efficiency" },
  { name: "DPR" },
  { name: "Network Architecture" },
  { name: "VMware ESX" },
  { name: "PDI" },
  { name: "PQRI" },
  { name: "Spring MVC" },
  { name: "Facilities Management" },
  { name: "Radio Advertising" },
  { name: "High Availability Clustering" },
  { name: "DMS-100" },
  { name: "Black Belt" },
  { name: "PKI" },
  { name: "Type 2 Diabetes" },
  { name: "IT Strategy" },
  { name: "MM modules" },
  { name: "Product Life Cycle" },
  { name: "Thermal Oxidation" },
  { name: "Vectorworks" },
  { name: "SNL" },
  { name: "ASP.NET AJAX" },
  { name: "Agility" },
  { name: "Thermodynamics" },
  { name: "Natural Gas" },
  { name: "Embedded Systems" },
  { name: "Raw Materials" },
  { name: "Layout" },
  { name: "PPBES" },
  { name: "Change Control" },
  { name: "DSLR" },
  { name: "GMS" },
  { name: "Language Teaching" },
  { name: "NICU" },
];
module.exports = { courses };
